server:
  port: 8087
  servlet:
    context-path: /booksMicroService

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/library?autoreconnect = true
    username: root
    password: root